# docker-compose.yml
version: '3'
services:
  postgresql:
    container_name: postgresql
    restart: always
    image: postgres:10.10
    environment:
      - POSTGRES_USER=cube
      - POSTGRES_PASSWORD=square
      - POSTGRES_DB=moviestore
    ports:
      - "5432:5432"
  server:
    container_name: server
    build:
      context: ./Server
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgresql
    depends_on:
      - postgresql
    ports:
      - '1234:1234'
    expose:
      - '1234'
  client:
    container_name: client
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
      - '3000:3000'
    expose:
      - '5000'
      - '3000'
    depends_on:
      - server